version: '3.8'

services:
  whatsapp-api:
    image: wppconnect/server-cli:latest
    container_name: whatsapp-api
    restart: always
    ports:
      - "21465:21465"
    environment:
      - PORT=21465
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./wppconnect-data:/usr/src/app/session
    command:
      - --secretKey=${SECRET_KEY}
      - --startAllSession
      - --webhook-url=http://flask-app:5000/webhook
      - --webhook-autoDownload
      - --webhook-readMessage
    networks:
      - app_network
    tty: true

  flask-app:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 bot:app --log-level debug --access-logfile -
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - whatsapp-api
      - redis
    env_file:
      - .env
    networks:
      - app_network

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
